# Generated by Django 2.0 on 2020-06-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=64, verbose_name='学生名')),
                ('password', models.CharField(max_length=32, verbose_name='用户密码')),
                ('sex', models.CharField(max_length=2, verbose_name='用户性别')),
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
