# Generated by Django 2.0 on 2020-06-21 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('cid', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='课程号')),
                ('name', models.CharField(max_length=128, verbose_name='课程名')),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.User')),
                ('name', models.CharField(max_length=64, verbose_name='学生名')),
                ('sex', models.CharField(max_length=8, verbose_name='性别')),
                ('stu_status', models.IntegerField(choices=[(0, '成功'), (1, '失败')], default=1, verbose_name='选修课程状态')),
                ('password', models.CharField(blank=True, max_length=32)),
                ('stucourse', models.ManyToManyField(to='Student.course', verbose_name='选修的课程')),
            ],
        ),
    ]
